In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [21]:
df=pd.DataFrame(pd.read_csv('./datasets/age_group.csv'))

In [22]:
df.head()

  age_group  class  gender play_circket
0     child      5    male          yes
1     child      5  female           no
2     child      6    male          yes
3      teen      8    male          yes
4      teen      8  female          yes

In [23]:
df.describe(include='all')

       age_group      class gender play_circket
count         10  10.000000     10           10
unique         3        NaN      2            2
top        child        NaN   male          yes
freq           4        NaN      5            6
mean         NaN   7.900000    NaN          NaN
std          NaN   2.884826    NaN          NaN
min          NaN   4.000000    NaN          NaN
25%          NaN   5.250000    NaN          NaN
50%          NaN   8.000000    NaN          NaN
75%          NaN   9.750000    NaN          NaN
max          NaN  12.000000    NaN          NaN

In [24]:
# entophy= -npyes log(pyes)-pn logp pn

In [26]:
# data of male who play cricket
male_play_cricket = df[(df['gender'] == 'male') & (df['play_circket'] == 'yes')]
male_play_cricket

  age_group  class gender play_circket
0     child      5   male          yes
2     child      6   male          yes
3      teen      8   male          yes
8      teen      9   male          yes

In [46]:
# data of male who  not play cricket
male_not_play_cricket = df[(df['gender'] == 'male') & (df['play_circket'] == 'no')]
male_not_play_cricket

  age_group  class gender play_circket
6    senior     12   male           no

In [38]:
#probalites of yes/no playing cricket
p_yes = len(df[df['play_circket'] == 'yes']) / len(df)
p_yes
p_no = len(df[df['play_circket'] == 'no']) / len(df)
p_no

0.4

In [48]:
# entrophy of male playing cricket
entropy_male_play_cricket = - (p_male_play_cricket * np.log2(p_male_play_cricket) + p_male_not_play_cricket * np.log2(p_male_not_play_cricket))
entropy_male_play_cricket

np.float64(0.860964047443681)

In [49]:
male = df[df["gender"] == "male"]["play_circket"]
female = df[df["gender"] == "female"]["play_circket"]

In [50]:
male_counts = male.value_counts()

p_yes = male_counts["yes"] / len(male)
p_no = male_counts["no"] / len(male)

male_entropy = - (p_yes * np.log2(p_yes) + p_no * np.log2(p_no))

male_entropy

np.float64(0.7219280948873623)

In [51]:
female_counts = female.value_counts()

p_yes = female_counts["yes"] / len(female)
p_no = female_counts["no"] / len(female)

female_entropy = - (p_yes * np.log2(p_yes) + p_no * np.log2(p_no))

female_entropy

np.float64(0.9709505944546686)

In [52]:
overall_counts = df["play_circket"].value_counts()

p_yes = overall_counts["yes"] / len(df)
p_no = overall_counts["no"] / len(df)

overall_entropy = - (p_yes * np.log2(p_yes) + p_no * np.log2(p_no))

overall_entropy

np.float64(0.9709505944546686)

In [53]:
weighted_entropy = (
    (len(male) / len(df)) * male_entropy +
    (len(female) / len(df)) * female_entropy
)

weighted_entropy

np.float64(0.8464393446710154)