# Pipeline

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [26]:
data= pd.read_csv('Datasets/healthData.csv')
data.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1

In [31]:
col=data.columns.tolist()

In [32]:
data.describe(include='all')

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
count,5110.000000,5110,5110.000000,5110.000000,5110.000000,5110,5110,5110,5110.000000,4909.000000,5110,5110.000000
unique,NaN,3,NaN,NaN,NaN,2,5,2,NaN,NaN,4,NaN
top,NaN,Female,NaN,NaN,NaN,Yes,Private,Urban,NaN,NaN,never smoked,NaN
freq,NaN,2994,NaN,NaN,NaN,3353,2925,2596,NaN,NaN,1892,NaN
mean,36517.829354,NaN,43.226614,0.097456,0.054012,NaN,NaN,NaN,106.147677,28.893237,NaN,0.048728
std,21161.721625,NaN,22.612647,0.296607,0.226063,NaN,NaN,NaN,45.283560,7.854067,NaN,0.215320
min,67.000000,NaN,0.080000,0.000000,0.000000,NaN,NaN,NaN,55.120000,10.300000,NaN,0.000000
25%,17741.250000,NaN,25.000000,0.000000,0.000000,NaN,NaN,NaN,77.245000,23.500000,NaN,0.000000
50%,36932.000000,NaN,45.000000,0.000000,0.000000,NaN,NaN,NaN,91.885000,28.100000,NaN,0.000000
75%,54682.000000,NaN,61.000000,0.000000,0.000000,NaN,NaN,NaN,114.090000,33.100000,NaN,0.000000
max,72940.000000,NaN,82.000000,1.000000,1.000000,NaN,NaN,NaN,271.740000,97.600000,NaN,1.000000

In [35]:
for col in data.columns:
    print(f"Unique values in '{col}': {data[col].unique()}")

Unique values in 'id': [ 9046 51676 31112 ... 19723 37544 44679]
Unique values in 'gender': <StringArray>
['Male', 'Female', 'Other']
Length: 3, dtype: str
Unique values in 'age': [6.70e+01 6.10e+01 8.00e+01 4.90e+01 7.90e+01 8.10e+01 7.40e+01 6.90e+01
 5.90e+01 7.80e+01 5.40e+01 5.00e+01 6.40e+01 7.50e+01 6.00e+01 5.70e+01
 7.10e+01 5.20e+01 8.20e+01 6.50e+01 5.80e+01 4.20e+01 4.80e+01 7.20e+01
 6.30e+01 7.60e+01 3.90e+01 7.70e+01 7.30e+01 5.60e+01 4.50e+01 7.00e+01
 6.60e+01 5.10e+01 4.30e+01 6.80e+01 4.70e+01 5.30e+01 3.80e+01 5.50e+01
 1.32e+00 4.60e+01 3.20e+01 1.40e+01 3.00e+00 8.00e+00 3.70e+01 4.00e+01
 3.50e+01 2.00e+01 4.40e+01 2.50e+01 2.70e+01 2.30e+01 1.70e+01 1.30e+01
 4.00e+00 1.60e+01 2.20e+01 3.00e+01 2.90e+01 1.10e+01 2.10e+01 1.80e+01
 3.30e+01 2.40e+01 3.40e+01 3.60e+01 6.40e-01 4.10e+01 8.80e-01 5.00e+00
 2.60e+01 3.10e+01 7.00e+00 1.20e+01 6.20e+01 2.00e+00 9.00e+00 1.50e+01
 2.80e+01 1.00e+01 1.80e+00 3.20e-01 1.08e+00 1.90e+01 6.00e+00 1.16e+00
 1.00e+00 1.40e+00 1.72e+00 2.40e-01 1.64e+00 1.56e+00 7.20e-01 1.88e+00
 1.24e+00 8.00e-01 4.00e-01 8.00e-02 1.48e+00 5.60e-01 4.80e-01 1.60e-01]
Unique values in 'hypertension': [0 1]
Unique values in 'heart_disease': [1 0]
Unique values in 'ever_married': <StringArray>
['Yes', 'No']
Length: 2, dtype: str
Unique values in 'work_type': <StringArray>
['Private', 'Self-employed', 'Govt_job', 'children', 'Never_worked']
Length: 5, dtype: str
Unique values in 'Residence_type': <StringArray>
['Urban', 'Rural']
Length: 2, dtype: str
Unique values in 'avg_glucose_level': [228.69 202.21 105.92 ...  82.99 166.29  85.28]
Unique values in 'bmi': [36.6  nan 32.5 34.4 24.  29.  27.4 22.8 24.2 29.7 36.8 27.3 28.2 30.9
 37.5 25.8 37.8 22.4 48.9 26.6 27.2 23.5 28.3 44.2 25.4 22.2 30.5 26.5
 33.7 23.1 32.  29.9 23.9 28.5 26.4 20.2 33.6 38.6 39.2 27.7 31.4 36.5
 33.2 32.8 40.4 25.3 30.2 47.5 20.3 30.  28.9 28.1 31.1 21.7 27.  24.1
 45.9 44.1 22.9 29.1 32.3 41.1 25.6 29.8 26.3 26.2 29.4 24.4 28.  28.8
 34.6 19.4 30.3 41.5 22.6 56.6 27.1 31.3 31.  31.7 35.8 28.4 20.1 26.7
 38.7 34.9 25.  23.8 21.8 27.5 24.6 32.9 26.1 31.9 34.1 36.9 37.3 45.7
 34.2 23.6 22.3 37.1 45.  25.5 30.8 37.4 34.5 27.9 29.5 46.  42.5 35.5
 26.9 45.5 31.5 33.  23.4 30.7 20.5 21.5 40.  28.6 42.2 29.6 35.4 16.9
 26.8 39.3 32.6 35.9 21.2 42.4 40.5 36.7 29.3 19.6 18.  17.6 19.1 50.1
 17.7 54.6 35.  22.  39.4 19.7 22.5 25.2 41.8 60.9 23.7 24.5 31.2 16.
 31.6 25.1 24.8 18.3 20.  19.5 36.  35.3 40.1 43.1 21.4 34.3 27.6 16.5
 24.3 25.7 21.9 38.4 25.9 54.7 18.6 24.9 48.2 20.7 39.5 23.3 64.8 35.1
 43.6 21.  47.3 16.6 21.6 15.5 35.6 16.7 41.9 16.4 17.1 29.2 37.9 44.6
 39.6 40.3 41.6 39.  23.2 18.9 36.1 36.3 46.5 16.8 46.6 35.2 20.9 13.8
 31.8 15.3 38.2 45.2 17.  49.8 27.8 60.2 23.  22.1 26.  44.3 51.  39.7
 34.7 21.3 41.2 34.8 19.2 35.7 40.8 24.7 19.  32.4 34.  28.7 32.1 51.5
 20.4 30.6 71.9 19.3 40.9 17.2 16.1 16.2 40.6 18.4 21.1 42.3 32.2 50.2
 17.5 18.7 42.1 47.8 20.8 30.1 17.3 36.4 12.  36.2 55.7 14.4 43.  41.7
 33.8 43.9 22.7 57.5 37.  38.5 16.3 44.  32.7 54.2 40.2 33.3 17.4 41.3
 52.3 14.6 17.8 46.1 33.1 18.1 43.8 50.3 38.9 43.7 39.9 15.9 19.8 12.3
 78.  38.3 41.  42.6 43.4 15.1 20.6 33.5 43.2 30.4 38.  33.4 44.9 44.7
 37.6 39.8 53.4 55.2 42.  37.2 42.8 18.8 42.9 14.3 37.7 48.4 50.6 46.2
 49.5 43.3 33.9 18.5 44.5 45.4 55.  54.8 19.9 17.9 15.6 52.8 15.2 66.8
 55.1 18.2 48.5 55.9 57.3 10.3 14.1 15.7 56.  44.8 13.4 51.8 38.1 57.7
 44.4 38.8 49.3 39.1 54.  56.1 97.6 53.9 13.7 11.5 41.4 14.2 49.4 15.4
 45.1 49.2 48.7 53.8 42.7 48.8 52.7 53.5 50.5 15.8 45.3 14.8 51.9 63.3
 40.7 61.2 48.  46.8 48.3 58.1 50.4 11.3 12.8 13.5 14.5 15.  59.7 47.4
 52.5 13.2 52.9 61.6 49.9 54.3 47.9 13.  13.9 50.9 57.2 64.4 92.  50.8
 57.9 45.8 47.6 14.  46.4 46.9 47.1 13.3 48.1 51.7 46.3 54.1 14.9]
Unique values in 'smoking_status': <StringArray>
['formerly smoked', 'never smoked', 'smokes', 'Unknown']
Length: 4, dtype: str
Unique values in 'stroke': [1 0]

In [36]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 5110 non-null   int64
 1   gender             5110 non-null   str
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64
 4   heart_disease      5110 non-null   int64
 5   ever_married       5110 non-null   str
 6   work_type          5110 non-null   str
 7   Residence_type     5110 non-null   str
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   str
 11  stroke             5110 non-null   int64
dtypes: float64(3), int64(4), str(5)
memory usage: 479.2 KB

In [37]:
data.duplicated().sum()

np.int64(0)

In [40]:
data.groupby('work_type').agg({'age': 'mean', 'stroke': 'mean'})

                     age    stroke
work_type
Govt_job       50.879756  0.050228
Never_worked   16.181818  0.000000
Private        45.503932  0.050940
Self-employed  60.201465  0.079365
children        6.841339  0.002911

In [41]:
age_bins = [0, 18, 35, 50, 65, np.inf]
age_labels = ["young", "adult", "middle-aged", "senior", "elderly"]
data['age_group'] = pd.cut(data['age'], bins=age_bins, labels=age_labels)
data.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,age_group
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,elderly
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1,senior
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,elderly
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,middle-aged
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,elderly

In [ ]:
# new col for risk who has likely to get stroke

,id,age,conditions,gender,visit,cost,cost_per_visit,age_group,risk
0,101,23,diabetic,M,1,1000,1000.000000,adult,low
1,102,34,hypertension,F,2,2200,1100.000000,adult,medium
2,103,45,asthma,M,3,1450,483.333333,middle-aged,medium
3,104,56,fever,F,1,3400,3400.000000,senior,low
4,105,67,ocd,M,5,2500,500.000000,elderly,high

In [ ]:
class pipeline:
    def __init__(self, file_path: str, output_dir: str = 'output') -> None:
        self.file_path = Path(file_path) if Path(file_path).exists() else Path('Datasets') / file_path
        self.output_dir = Path(output_dir) if Path(output_dir).exists() else Path('Datasets') / output_dir
        self.output_dir.mkdir(exist_ok=True)

    def load(self) -> pd.DataFrame:
        try:
            df = pd.read_csv(self.file_path)
            print("Data loaded")
            return df
        except Exception as e:
            print("Error loading data")
            return pd.DataFrame()

    def transform(self, df: pd.DataFrame) -> pd.DataFrame:
        df['cost_per_visit'] = df['cost'] / df['visit']
        age_bins = [0, 18, 35, 50, 65, np.inf]
        age_labels = ["young", "adult", "middle-aged", "senior", "elderly"]
        df['age_group'] = pd.cut(df['age'], bins=age_bins, labels=age_labels)
        df['risk'] = pd.cut(df['visit'], bins=[0, 1, 3, np.inf], labels=['low', 'medium', 'high'])
        print("Data transformed")
        return df

    def export(self, df: pd.DataFrame, filename: str) -> None:
        output_path = self.output_dir / filename
        try:
            df.to_csv(output_path, index=False)
            print(f"Data exported to {output_path}")
        except Exception as e:
            print(f"Error exporting data: {e}")


pipeline = pipeline('Datasets/health_dataset.csv')
raw_df = pipeline.load()    
prepared_df = pipeline.transform(raw_df)    
pipeline.export(prepared_df, 'transformed_health_data.csv')

prepared_df.head()

Data loaded
Data transformed
Data exported to Datasets\output\transformed_health_data.csv

,id,age,conditions,gender,visit,cost,cost_per_visit,age_group,risk
0,101,23,diabetic,M,1,1000,1000.000000,adult,low
1,102,34,hypertension,F,2,2200,1100.000000,adult,medium
2,103,45,asthma,M,3,1450,483.333333,middle-aged,medium
3,104,56,fever,F,1,3400,3400.000000,senior,low
4,105,67,ocd,M,5,2500,500.000000,elderly,high